import type { SupportedLanguage } from '@/i18n/messages';

/**
 * The pages a search engine can actually read.
 *
 * The game itself renders its loading screen into the static document — eight words, one of
 * them "A preparar…" — so `/` gives a crawler nothing to rank and the two languages the app
 * already speaks are invisible to it. These do the explaining: what the puzzle is, how it is
 * played, and why it is not a Sudoku, each in its own language at its own URL.
 *
 * Copy rather than UI strings, so it lives here and not in `messages.ts`. Prose in the
 * catalogue would fight the parity test that keeps the three interfaces in step, and none of
 * this is ever shown inside the app.
 */
export interface GuideSection {
  title: string;
  body: string;
}

export interface Guide {
  language: SupportedLanguage;
  /**
   * Named in its own language: a URL is read by the people the page is for. Plain `string`
   * rather than `Href`, because the typed-route union is generated by the dev server and a
   * fresh route is absent from it until that runs — the export builds the page regardless.
   */
  path: string;
  /** `<title>`, which every route was inheriting from the root layout until now. */
  title: string;
  description: string;
  heading: string;
  intro: string;
  rules: GuideSection[];
  difference: GuideSection;
  pitch: string;
  play: string;
  elsewhere: string;
  ogLocale: string;
}

export const GUIDES: Record<SupportedLanguage, Guide> = {
  'pt-PT': {
    language: 'pt-PT',
    path: '/como-jogar',
    title: 'Como jogar Bumi · Puzzle de retângulos',
    description:
      'As regras do Shikaku em três passos: divide a grelha em retângulos, um por número, sem sobras nem sobreposições. Joga grátis no browser, sem instalar.',
    heading: 'Como jogar Bumi',
    intro:
      'O Bumi é um puzzle de lógica japonês, conhecido por Shikaku. Recebes uma grelha com números espalhados e divides o tabuleiro inteiro em retângulos — um para cada número.',
    rules: [
      {
        title: 'Um retângulo por número',
        body: 'Cada número fica dentro de exatamente um retângulo, e cada retângulo contém exatamente um número. Nunca dois, nunca nenhum.',
      },
      {
        title: 'O número é a área',
        body: 'Um 6 desenha um retângulo de seis quadrados. Pode ser 1×6, 6×1, 2×3 ou 3×2 — escolher qual é o jogo.',
      },
      {
        title: 'Sem sobras nem sobreposições',
        body: 'Quando o tabuleiro estiver todo coberto e nenhum retângulo cruzar outro, está resolvido. Cada puzzle tem uma solução única.',
      },
    ],
    difference: {
      title: 'Não é um Sudoku',
      body: 'Um Sudoku pede-te para eliminar hipóteses casa a casa. Aqui pensas em formas: de quantas maneiras cabe este número, e qual delas não rouba o espaço de que o vizinho vai precisar. Chega-se sempre à solução por lógica — nunca é preciso adivinhar.',
    },
    pitch:
      '500 níveis a subir de dificuldade, um desafio diário igual para toda a gente, e um modo treino que gera puzzles sem fim. Grátis, no browser, sem instalar nada.',
    play: 'Jogar agora',
    elsewhere: 'Noutras línguas',
    ogLocale: 'pt_PT',
  },
  en: {
    language: 'en',
    path: '/how-to-play',
    title: 'How to play Bumi · Rectangle logic puzzle',
    description:
      'Shikaku rules in three steps: split the grid into rectangles, one per number, with no gaps and no overlaps. Play free in your browser, nothing to install.',
    heading: 'How to play Bumi',
    intro:
      'Bumi is a Japanese logic puzzle, known as Shikaku. You get a grid with numbers scattered across it, and you divide the whole board into rectangles — one for each number.',
    rules: [
      {
        title: 'One rectangle per number',
        body: 'Every number sits inside exactly one rectangle, and every rectangle holds exactly one number. Never two, never none.',
      },
      {
        title: 'The number is the area',
        body: 'A 6 draws a rectangle of six squares. It can be 1×6, 6×1, 2×3 or 3×2 — working out which is the game.',
      },
      {
        title: 'No gaps, no overlaps',
        body: 'When the board is fully covered and no rectangle crosses another, it is solved. Every puzzle has exactly one solution.',
      },
    ],
    difference: {
      title: 'It is not a Sudoku',
      body: 'A Sudoku asks you to eliminate candidates cell by cell. Here you think in shapes: how many ways this number fits, and which of them does not steal the room its neighbour is going to need. The solution is always reachable by logic — you never have to guess.',
    },
    pitch:
      '500 levels that climb in difficulty, a daily challenge everyone gets the same board for, and a practice mode that generates puzzles endlessly. Free, in the browser, nothing to install.',
    play: 'Play now',
    elsewhere: 'In other languages',
    ogLocale: 'en_GB',
  },
  es: {
    language: 'es',
    path: '/como-jugar',
    title: 'Cómo jugar a Bumi · Puzle de rectángulos',
    description:
      'Las reglas del Shikaku en tres pasos: divide la cuadrícula en rectángulos, uno por número, sin huecos ni solapamientos. Juega gratis en el navegador, sin instalar nada.',
    heading: 'Cómo jugar a Bumi',
    intro:
      'Bumi es un puzle de lógica japonés, conocido como Shikaku. Recibes una cuadrícula con números repartidos y divides todo el tablero en rectángulos — uno por cada número.',
    rules: [
      {
        title: 'Un rectángulo por número',
        body: 'Cada número queda dentro de exactamente un rectángulo, y cada rectángulo contiene exactamente un número. Nunca dos, nunca ninguno.',
      },
      {
        title: 'El número es el área',
        body: 'Un 6 dibuja un rectángulo de seis casillas. Puede ser 1×6, 6×1, 2×3 o 3×2 — averiguar cuál es el juego.',
      },
      {
        title: 'Sin huecos ni solapamientos',
        body: 'Cuando el tablero esté cubierto por completo y ningún rectángulo cruce a otro, está resuelto. Cada puzle tiene una única solución.',
      },
    ],
    difference: {
      title: 'No es un Sudoku',
      body: 'Un Sudoku te pide descartar candidatos casilla a casilla. Aquí piensas en formas: de cuántas maneras cabe este número, y cuál de ellas no le roba el sitio que su vecino va a necesitar. Siempre se llega por lógica — nunca hace falta adivinar.',
    },
    pitch:
      '500 niveles que suben de dificultad, un reto diario con el mismo tablero para todos, y un modo entrenamiento que genera puzles sin fin. Gratis, en el navegador, sin instalar nada.',
    play: 'Jugar ahora',
    elsewhere: 'En otros idiomas',
    ogLocale: 'es_ES',
  },
};

export const GUIDE_LANGUAGES = Object.keys(GUIDES) as SupportedLanguage[];

/** What the language links say: each names itself, so it reads to the person it is for. */
export const GUIDE_ENDONYMS: Record<SupportedLanguage, string> = {
  'pt-PT': 'Português',
  en: 'English',
  es: 'Español',
};
