// One-off script: regenerates all campaign levels with the uniqueness-verifying
// generator and bakes them into src/game/levels.data.ts. Run with:
//   npx tsx scripts/generateLevels.ts
import { writeFileSync } from 'node:fs';
import { join } from 'node:path';
import { getSolutionFingerprint } from '../src/game/catalog';
import { DIFFS, getCampaignLevelMeta } from '../src/game/difficulty';
import { genUniqueLevel } from '../src/game/generateUnique';
import { HARDCODED_LEVELS } from '../src/game/levels';
import { gradeLevel } from '../src/game/logicSolver';
import { isUnique } from '../src/game/solver';
import type { Level, LevelMeta } from '../src/game/types';

const LEVEL_META: LevelMeta[] = getCampaignLevelMeta();

let confirmedUnique = 0;
let solvableByLogic = 0;
const deepestHistogram = new Map<number, number>();
const usedSolutionFingerprints = new Set(Object.values(HARDCODED_LEVELS).map(getSolutionFingerprint));

// Clue-position refinement is the single largest difficulty gain in the pipeline, which is
// exactly why the opening levels don't get it. Ungated it took levels 51-100 from depth 1.70
// to 3.20 — the third and fourth tier a new player ever meets, playing harder than the old
// campaign's endgame. Levels 1-100 (all of Fácil plus the first Médio tier) keep the clue
// positions the generator picked; everything past that gets the full hill climb.
const REFINE_FROM_INDEX = 100;

function generateDistinctLevel(index: number, meta: LevelMeta): Level {
  const seed = index * 1031 + 7;
  const maxVariants = 240;
  let uniqueButGuessy: Level | null = null;

  for (let variant = 0; variant < maxVariants; variant++) {
    const level = genUniqueLevel(seed + variant * 104_729, meta.size, meta.maxArea, meta.hard, meta.challenge, {
      clueTarget: meta.clueTarget,
      clueRange: meta.clueRange,
      // Worth the ~80ms per level here: this is a one-off bake. See REFINE_FROM_INDEX.
      refine: index >= REFINE_FROM_INDEX,
    });
    const fingerprint = getSolutionFingerprint(level);
    if (usedSolutionFingerprints.has(fingerprint)) continue;

    // Prefer levels a player can finish by deduction alone. Only settle for a
    // merely-unique one if the whole variant pool fails to produce a fair puzzle.
    if (!gradeLevel(level).solvedByLogic) {
      if (!uniqueButGuessy && isUnique(level)) uniqueButGuessy = level;
      continue;
    }
    usedSolutionFingerprints.add(fingerprint);
    return level;
  }

  if (uniqueButGuessy) {
    usedSolutionFingerprints.add(getSolutionFingerprint(uniqueButGuessy));
    return uniqueButGuessy;
  }

  throw new Error(`Could not generate a distinct unique solution for level ${index + 1}`);
}

const generated: Level[] = [];
for (let idx = 0; idx < LEVEL_META.length; idx++) {
  generated.push(generateDistinctLevel(idx, LEVEL_META[idx]));
  if ((idx + 1) % 50 === 0) {
    process.stderr.write(`  ...${idx + 1}/${LEVEL_META.length}\n`);
  }
}

// Order each tier by measured difficulty so the ramp is monotone by construction rather
// than by hope — generation is stochastic, so without this a level can easily be harder
// than the one twenty slots after it.
//
// Milestone slots stay pinned: they are every tenth index, the runtime keys hint behaviour
// off that index, so their levels must not drift to another position. Only the ordinary
// slots within a tier are permuted, and only among themselves.
const scores = generated.map(level => gradeLevel(level).score);
const levels: Level[] = generated.slice();

let tierStart = 0;
for (const tier of DIFFS) {
  const tierEnd = tierStart + tier.count;
  const ordinarySlots: number[] = [];
  for (let idx = tierStart; idx < tierEnd; idx++) {
    if (!LEVEL_META[idx].milestone) ordinarySlots.push(idx);
  }

  const ordered = ordinarySlots.slice().sort((a, b) => scores[a] - scores[b]);
  ordinarySlots.forEach((slot, i) => {
    levels[slot] = generated[ordered[i]];
  });

  tierStart = tierEnd;
}

for (const level of levels) {
  if (isUnique(level)) confirmedUnique++;
  const grade = gradeLevel(level);
  if (grade.solvedByLogic) solvableByLogic++;
  deepestHistogram.set(grade.deepest, (deepestHistogram.get(grade.deepest) ?? 0) + 1);
}

const difficulty = levels.map(level => gradeLevel(level).score);

const out = `// AUTO-GENERATED by scripts/generateLevels.ts — do not edit by hand.
import type { Level } from './types';

export const CAMPAIGN_LEVELS: Level[] = ${JSON.stringify(levels)};

// logicSolver.ts score for the level at the same index: the hardest deduction technique it
// forces, weighted, plus how much work each technique took. Sorted ascending within tier.
export const CAMPAIGN_DIFFICULTY: number[] = ${JSON.stringify(difficulty)};
`;

writeFileSync(join(__dirname, '../src/game/levels.data.ts'), out);

const histogram = [...deepestHistogram]
  .sort((a, b) => a[0] - b[0])
  .map(([deepest, count]) => `${deepest}:${count}`)
  .join('  ');

let regressions = 0;
for (let i = 1; i < difficulty.length; i++) {
  if (difficulty[i] < difficulty[i - 1]) regressions++;
}

process.stderr.write(
  `Done. ${confirmedUnique}/${LEVEL_META.length} levels confirmed unique-solution ` +
    `(${LEVEL_META.length - confirmedUnique} fell back to best-effort).\n` +
    `${solvableByLogic}/${LEVEL_META.length} solvable by deduction alone — the rest need a guess.\n` +
    `Hardest technique required (1=forcedShape 2=soleCoverage 3=sharedCell 4=contradiction 5=guess): ${histogram}\n` +
    `Difficulty dips vs previous level: ${regressions}/${difficulty.length - 1} (tier boundaries and pinned milestones account for these).\n`,
);
